# Godly AI System Configuration

# System-wide settings
system:
  name: "Godly AI"
  version: "0.1.0"
  log_level: "INFO"
  random_seed: 42

# Neuromorphic core settings
neuromorphic:
  # Liquid State Machine configuration
  lsm:
    reservoir_size: 1000
    input_dim: 100
    spectral_radius: 0.95
    leak_rate: 0.1
    connectivity: 0.1
  
  # Spiking neuron parameters
  neurons:
    threshold: 1.0
    reset_potential: 0.0
    tau_mem: 20.0  # membrane time constant (ms)
    tau_syn: 5.0   # synaptic time constant (ms)
    refractory_period: 2.0  # ms
  
  # STDP learning parameters
  stdp:
    tau_plus: 20.0   # ms
    tau_minus: 20.0  # ms
    a_plus: 0.01
    a_minus: 0.012
    w_max: 1.0
    w_min: 0.0

# Memory system configuration
memory:
  # Working memory settings
  working:
    capacity: 1000
    decay_rate: 0.1
    attention_threshold: 0.5
  
  # Episodic memory settings
  episodic:
    max_episodes: 10000
    compression_threshold: 0.8
    replay_batch_size: 32
  
  # Semantic memory settings
  semantic:
    graph_size: 50000
    embedding_dim: 256
    similarity_threshold: 0.7
  
  # Meta-memory settings
  meta:
    learning_history_size: 1000
    adaptation_rate: 0.01

# Multi-modal reasoning configuration
reasoning:
  # Visual reasoning
  visual:
    input_channels: 3
    spatial_resolution: [224, 224]
    temporal_window: 10
  
  # Audio reasoning
  audio:
    sample_rate: 16000
    n_mels: 80
    hop_length: 512
  
  # Text reasoning
  text:
    vocab_size: 50000
    max_sequence_length: 512
    embedding_dim: 256
  
  # Motor reasoning
  motor:
    action_dim: 10
    control_frequency: 100  # Hz

# Self-modification settings
self_modification:
  # Topology evolution
  topology:
    mutation_rate: 0.01
    selection_pressure: 0.1
    max_connections: 100000
  
  # Meta-learning
  meta_learning:
    learning_rate_adaptation: true
    hyperparameter_search: true
    architecture_search: true

# Intrinsic motivation configuration
motivation:
  # Curiosity settings
  curiosity:
    novelty_threshold: 0.5
    exploration_rate: 0.1
    interest_decay: 0.95
  
  # Goal emergence
  goals:
    complexity_growth: 0.05
    max_active_goals: 10
    goal_timeout: 1000  # steps

# Training configuration
training:
  # General training settings
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 1000
  early_stopping_patience: 50
  
  # Unsupervised learning
  unsupervised:
    pattern_discovery_threshold: 0.8
    clustering_algorithm: "som"  # self-organizing map
    adaptation_rate: 0.01
  
  # Validation settings
  validation:
    split_ratio: 0.2
    validation_frequency: 10  # epochs

# Storage configuration
storage:
  # Redis settings (real-time memory)
  redis:
    host: "localhost"
    port: 6379
    db: 0
    max_connections: 100
  
  # SQLite settings (persistent storage)
  sqlite:
    database_path: "data/godly_ai.db"
    connection_pool_size: 10
  
  # HDF5 settings (large-scale data)
  hdf5:
    data_path: "data/network_states.h5"
    compression: "gzip"
    chunk_size: 1000

# Performance optimization
optimization:
  # CPU optimization
  cpu:
    use_mkl: true
    num_threads: -1  # use all available cores
    vectorization: true
  
  # Memory optimization
  memory:
    garbage_collection: true
    memory_mapping: true
    compression: true
  
  # JIT compilation
  jit:
    use_numba: true
    cache_compiled_functions: true

# Monitoring and logging
monitoring:
  # Performance metrics
  metrics:
    collection_frequency: 1.0  # seconds
    retention_period: 86400    # seconds (24 hours)
  
  # Logging configuration
  logging:
    log_file: "logs/godly_ai.log"
    max_file_size: "100MB"
    backup_count: 5
  
  # Visualization
  visualization:
    update_frequency: 5.0  # seconds
    max_plot_points: 1000

# API configuration
api:
  # REST API settings
  rest:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    timeout: 30
  
  # Authentication
  auth:
    enabled: false
    secret_key: "your-secret-key-here"
    algorithm: "HS256"
    access_token_expire_minutes: 30

# Hardware configuration
hardware:
  # CPU settings
  cpu:
    target_architecture: "x86_64"
    optimization_level: "O3"
  
  # Memory settings
  memory:
    max_ram_usage: "8GB"
    swap_usage: false
  
  # Training hardware
  training:
    device: "cpu"  # or "cuda" if available
    max_vram_usage: "8GB"